# 1. 벡터, 파트1: 벡터와 벡터의 기본 연산

선형대수학 응용 분야에서는 리스트 타입은 잘 사용하지 않고 NumPy 배열로 생성하여 사용

In [10]:
import numpy as np

asList = [1, 2, 3] # 리스트 타입
asArray = np.array([1, 2, 3]) # 1차원 배열 ~ 방향이 없는 배열
rowVec = np.array([ [1, 2, 3] ]) # 행벡터
colVec = np.array([ [1], [2], [3] ]) # 열벡터

print('-'*30)
print('리스트\n', asList)
print(f'type: {type(asList)}')
print(f'asList: {np.shape(asList)}')
print('-'*30)
print('1차원 배열\n', asArray)
print(f'type: {type(asArray)}')
print(f'asArray: {np.shape(asArray)}')
print('-'*30)
print('행벡터\n', rowVec)
print(f'type: {type(rowVec)}')
print(f'rowVec: {np.shape(rowVec)}')
print('-'*30)
print('열벡터\n', colVec)
print(f'type: {type(colVec)}')
print(f'colVec: {np.shape(colVec)}')
print('-'*30)

------------------------------
리스트
 [1, 2, 3]
type: <class 'list'>
asList: (3,)
------------------------------
1차원 배열
 [1 2 3]
type: <class 'numpy.ndarray'>
asArray: (3,)
------------------------------
행벡터
 [[1 2 3]]
type: <class 'numpy.ndarray'>
rowVec: (1, 3)
------------------------------
열벡터
 [[1]
 [2]
 [3]]
type: <class 'numpy.ndarray'>
colVec: (3, 1)
------------------------------


## 벡터 연산

In [23]:
v = np.array([ [4, 5, 6] ])
w = np.array([ [10, 20, 30] ])
u = np.array([ [0, 3, 6, 9] ])
print(f'v: {v}\n\nw: {w}\n\n u: {u}')
print('-'*40)

print('transpose')
print(f'v: {v.T}\n\nw: {w.T}\n\nu: {u.T}')

v: [[4 5 6]]

w: [[10 20 30]]

 u: [[0 3 6 9]]
----------------------------------------
transpose
v: [[4]
 [5]
 [6]]

w: [[10]
 [20]
 [30]]

u: [[0]
 [3]
 [6]
 [9]]


In [24]:
# 두 벡터의 덧셈 - 1
vPlusW = v + w
print(vPlusW)

[[14 25 36]]


In [25]:
# 두 벡터의 덧셈 - 2
uPlusW = u + w
print(uPlusW)

ValueError: operands could not be broadcast together with shapes (1,4) (1,3) 

In [37]:
# 브로드캐스팅
v = np.array([ [4, 5, 6] ]) # rowVec
w = np.array([ [10, 20, 30] ]).T # colVec(Transpose of w)
print(v + w)

print('-'*30)

v = np.array([ [1, 2, 3] ]).T
w = np.array([ [10, 20] ])
print(v + w)

# [1 1]   [10 20]
# [2 2] + [10 20]
# [3 3]   [10 20]

[[14 15 16]
 [24 25 26]
 [34 35 36]]
------------------------------
[[11 21]
 [12 22]
 [13 23]]


In [27]:
# 스칼라-벡터 곱셈
s = 2
a = [3, 4, 5] # 리스트
b = np.array(a) # np 배열

print(a * s)
print(b * s)

[3, 4, 5, 3, 4, 5]
[ 6  8 10]


- 주의! 파이썬의 리스트의 경우 리스트에 스칼라를 곱하면 리스트를 반복함
    - 이 방식은 선형대수학의 스칼라-벡터 곱셈이 아님

In [29]:
# 스칼라-벡터 덧셈
# 선형대수학에서는 스칼라+벡터가 불가능. but 파이썬과 같은 프로그램에서는 가능
s = 2
v = np.array([3, 6])
s + v

array([5, 8])

In [38]:
# 내적
v = np.array([1, 2, 3, 4])
w = np.array([5, 6, 7, 8])
np.dot(v, w)

70

In [39]:
s = 10
np.dot(s*v, w)

700

In [40]:
s = 20
np.dot(s*v, w)

1400

In [41]:
s = -1
np.dot(s*v, w)

-70

In [42]:
# 내적의 분배 법칙
a = np.array([ 0, 1, 2 ])
b = np.array([ 3, 5, 8 ])
c = np.array([ 13, 21, 34 ])

res1 = np.dot( a, b+c )
res2 = np.dot( a, b ) + np.dot( a, c )
print(res1, res2)

110 110


In [47]:
# 아다마르곱
a = np.array([5, 4, 8, 2])
b = np.array([1, 0, .5, -1])
a * b

array([ 5.,  0.,  4., -2.])