In [3]:
import numpy as np

In [4]:
# column vector
c = np.array([1, 2, 3])
print(c.shape)

# obtaining a particular entry
print(c[0])

(3,)
1


In [5]:
# row vector
r = np.array([ [1, 2, 3] ])
print(r.shape)

# obtaining a particular entry
print(r[0, 1])

(1, 3)
2


In [6]:
# creating a matrix with all zeros
a = np.zeros((2, 2))
print(a)

# creating a matrix with all ones
b = np.ones((2, 2))
print(b)

# creating a maxtrix filled with the same constant
c = np.full((2, 2), 7)
print(c)

# creating a matrix with random values
d = np.random.random((2, 2))
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.74695981 0.00998379]
 [0.01437073 0.16292089]]


In [7]:
# creating a matrix
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
# creating another matix
B = np.array([[11, 12, 13, 14],
              [15, 16, 17, 18]])
print(B)

[[11 12 13 14]
 [15 16 17 18]]


In [10]:
# transpose of A
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [11]:
# matrix-matrix multiplication
np.dot(A, B)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [12]:
# matrix-matrix multiplication
# size should match!
np.dot(B, A)

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [23]:
# coeeficient matrix A and a vector b
A = np.array([[60, 5.5, 1],
              [65, 5.0, 0],
              [55, 6.0, 1]])
b = np.array([66, 70, 78])

In [24]:
# idenetity matrix
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# computing an inverse
from numpy.linalg import inv
A_inv = inv(A)
A_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [26]:
# wrong matrix multiplication
A * A_inv

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [31]:
# correct matrix multiplication
A.dot(A_inv)

array([[ 1.00000000e+00,  0.00000000e+00, -7.77156117e-16],
       [ 1.11022302e-15,  1.00000000e+00, -1.11022302e-15],
       [ 4.44089210e-16,  0.00000000e+00,  1.00000000e+00]])

In [32]:
# solution of a linear system
x = A_inv.dot(b)
x

array([ -0.43478261,  19.65217391, -16.        ])

In [33]:
# a better way to solve the same linear system
# linear system에서 x를 바로 구해주는 함수: solve()
from numpy.linalg import solve
x = solve(A, b)
x

array([ -0.43478261,  19.65217391, -16.        ])