In [4]:
import numpy as np

# 1. 선형 가중 결합

In [23]:
l1, l2, l3 = 1, 2, -3 # l1, l2, l3은 각각 가중치(weights)
v1 = np.array([4, 5, 1])
v2 = np.array([-4, 0, -4])
v3 = np.array([1, 3, 2])

print(f'w = (l1 * v1) + (l2 * v2) + (l3 * v3)')
print(f'  = ({l1} * {v1}) + ({l2} * {v2}) + ({l3} * {v3})')
print(f'  = {l1*v1 + l2*v2 + l3*v3}')

w = (l1 * v1) + (l2 * v2) + (l3 * v3)
  = (1 * [4 5 1]) + (2 * [-4  0 -4]) + (-3 * [1 3 2])
  = [ -7  -4 -13]


# 2. 선형 독립성

In [48]:
V = np.array([ [1, 3], [2, 7] ])
S = np.array([ [1, 3], [2, 6] ])

print(f'Vector V is linearly independent. \n{V}\n')
print(f'Vector S is linearly dependent. \n{S}')

Vector V is linearly independent. 
[[1 3]
 [2 7]]

Vector S is linearly dependent. 
[[1 3]
 [2 6]]


In [56]:
T = np.array([ [8, -4, 14, 6], [4, 6, 0, 3], [14, 2, 4, 7], [13, 2, 9, 8] ])
T

array([[ 8, -4, 14,  6],
       [ 4,  6,  0,  3],
       [14,  2,  4,  7],
       [13,  2,  9,  8]])

# 3. 기저

In [57]:
S2 = np.array([ [1, 0], [0, 1] ])
S3 = np.array([ [1, 0, 0], [0, 1, 0], [0, 0, 1] ])

print(S2)
print()
print(S3)

[[1 0]
 [0 1]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [58]:
T = np.array([ [3, 1], [-3, 1] ])
print(T)

[[ 3  1]
 [-3  1]]
